GET http://localhost:5000/collections/amaze-bars

###

POST http://localhost:5000/user/profile
Content-Type: application/json

{
    "email":"check@gmail.com",
    "password":"check userRoute"
}

###

POST http://localhost:5000/account/register
Content-Type: application/json

{
    "id":"asdassdasdasd",
    "first_name":"checkConnectToDB",
    "last_name":"checkConnectToDB",
    "password":"checkConnectToDB",
    "email":"D@gmail.com",
    "order_history":[],
    "addresses":[]
}



